name = "snapurl-web-ui"
main = "workers-site/index.js"
compatibility_date = "2024-01-01"

#[site]
#bucket = "./client/dist"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[assets]
directory = "./client/dist"
binding = "ASSETS"
