name = "prosms-snapurl-web-ui"
main = "workers-site/index.js"
compatibility_date = "2024-01-01"
preview_urls: false

[[routes]]
pattern = "www.url.prosms.gr"
custom_domain = true

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[assets]
directory = "./client/dist"
binding = "ASSETS"

[vars]
VITE_API_BASE_URL = "https://server.url.prosms.gr/api"
VITE_AUTH_DOMAIN = "cytech.cloudflareaccess.com"
VITE_WORKER_URL = "https://url.prosms.gr"
