name = "snapurl-web-ui"
main = "workers-site/index.js"
compatibility_date = "2024-01-01"
preview_urls = false

[[routes]]
pattern = "www.url.racket.gr"
custom_domain = true

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "./client/dist"
binding = "ASSETS"
