name = "snapurl-web-ui-server"
main = "index.js"
compatibility_date = "2024-01-01"



[[kv_namespaces]]
binding = "SNAPURL_KV"
id = "bb0b757c25914a818f3d0c146371d780"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
