name = "snapurl-web-ui-server"
main = "index.js"
compatibility_date = "2024-01-01"



[[kv_namespaces]]
binding = "SNAPURL_KV"
id = "6c3ecbd5f8a043978c0d2959544acf75"


[vars]
CORS_ALLOWED_ORIGIN = "https://www.url.prosms.gr"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
